- name: db configuration
  hosts: db_server
  vars:
    ansible_ssh_private_key_file: "/home/ec2-user/key.pem"
  roles:
    - mariadb

- name: web server configuration
  hosts: web_server
  vars:
    ansible_ssh_private_key_file: "/home/ec2-user/key.pem"
  roles:
    - apache2